gpu: 0
seed: 2020

model:
  input_channels: 1
  out_channels: 16
  input_sensors: ['Vis', 'Inf']
  coder_layers: 4
  decoder_layers: 4
  # 新增 encoder
  encoder_pth: '/root/autodl-tmp/Graduate_XJTU/checkpoint/fusion_model.pth'
  n_feat: 64
  emb_dim: 512


train_config:
  num_epoch: 50
  nThreads: 4
  amp: true
  optim: "adam"
  scheduler: null
  resume: null
  deterministic: true 
  momentum: 0.9
  weight_decay: 0.0005
  lr_start: 0.001 
  power: 0.9
  warmup_steps: 100
  batch_size: 24
  patch: 192
  lr: 0.00001
  c_intensity: 3000
  c_detail: 3000
  eta: 0.5
  warmup_start_lr: 0.00001 


Prismer:
  dataset: 'demo'
  data_path: 'helpers'
  label_path: 'helpers/labels'
  experts: ['infred']  # 'none' for PrismerZ

  image_resolution: 480
  prismer_model: 'prismer_base'  # 'prismer-large' for Prismer(Z)-Large
  freeze: 'freeze_vision'

  prefix: 'A picture of'

Data_Acquisition:
  ir_image_path: "E:\\project\\yang\\data\\21_pairs_tno\\ir"
  vis_image_path: "E:\\project\\yang\\data\\21_pairs_tno\\vis"
  test_irimage_path: "E:\\project\\code\\multitask2023\\M3FD-simplified\\ir\\half-size"
  test_visimage_path: "E:\\project\\code\\multitask2023\\M3FD-simplified\\vis\\half-size"
  kaist_path: "/root/autodl-tmp/dataset/KAIST/"
  patch: 192

loss:
  loss_alpha: 0.2
  loss_beta: 0.167
  loss_gamma: 20
  loss_alpha2: 0.000001
  loss_style: 1
  loss_patch: 2
  loss_patch_alpha: 130
  log_dir: "./fusion_train_log"
  feature_num: 32